// Projects
export const GET_PROJECTS = "GET_PROJECTS";
export const GET_PROJECTS_LOADING = "GET_PROJECTS_LOADING";
export const GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS";
export const GET_PROJECTS_FAILURE = "GET_PROJECTS_FAILURE";
export const SET_ACTIVE_PROJECT = "SET_ACTIVE_PROJECT";
export const CREATE_PROJECT = "CREATE_PROJECT";
export const CREATE_PROJECT_LOADING = "CREATE_PROJECT_LOADING";
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";
export const CREATE_PROJECT_FAILURE = "CREATE_PROJECT_FAILURE";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const UPDATE_PROJECT_LOADING = "UPDATE_PROJECT_LOADING";
export const UPDATE_PROJECT_SUCCESS = "UPDATE_PROJECT_SUCCESS";
export const UPDATE_PROJECT_FAILURE = "UPDATE_PROJECT_FAILURE";
export const REFRESH_PROJECTS = "REFRESH_PROJECTS";
export const CREATE_PROJECT_IMAGE = "CREATE_PROJECT_IMAGE";
export const CREATE_PROJECT_IMAGE_LOADING = "CREATE_PROJECT_IMAGE_LOADING";
export const CREATE_PROJECT_IMAGE_SUCCESS = "CREATE_PROJECT_IMAGE_SUCCESS";
export const CREATE_PROJECT_IMAGE_FAILURE = "CREATE_PROJECT_IMAGE_FAILURE";
export const DELETE_PROJECT_IMAGE = "DELETE_PROJECT_IMAGE";
export const DELETE_PROJECT_IMAGE_LOADING = "DELETE_PROJECT_IMAGE_LOADING";
export const DELETE_PROJECT_IMAGE_SUCCESS = "DELETE_PROJECT_IMAGE_SUCCESS";
export const DELETE_PROJECT_IMAGE_FAILURE = "DELETE_PROJECT_IMAGE_FAILURE";
export const MOVE_PROJECT_IMAGE = "MOVE_PROJECT_IMAGE";
export const MOVE_PROJECT_IMAGE_LOADING = "MOVE_PROJECT_IMAGE_LOADING";
export const MOVE_PROJECT_IMAGE_SUCCESS = "MOVE_PROJECT_IMAGE_SUCCESS";
export const MOVE_PROJECT_IMAGE_FAILURE = "MOVE_PROJECT_IMAGE_FAILURE";
export const MAKE_PRIMARY_PROJECT_IMAGE = "MAKE_PRIMARY_PROJECT_IMAGE";
export const MAKE_PRIMARY_PROJECT_IMAGE_LOADING =
  "MAKE_PRIMARY_PROJECT_IMAGE_LOADING";
export const MAKE_PRIMARY_PROJECT_IMAGE_FAILURE =
  "MAKE_PRIMARY_PROJECT_IMAGE_FAILURE";
export const MAKE_PRIMARY_PROJECT_IMAGE_SUCCESS =
  "MAKE_PRIMARY_PROJECT_IMAGE_SUCCESS";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const DELETE_PROJECT_LOADING = "DELETE_PROJECT_LOADING";
export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS";
export const DELETE_PROJECT_FAILURE = "DELETE_PROJECT_FAILURE";
export const MOVE_PROJECT = "MOVE_PROJECT";
export const MOVE_PROJECT_LOADING = "MOVE_PROJECT_LOADING";
export const MOVE_PROJECT_SUCCESS = "MOVE_PROJECT_SUCCESS";
export const MOVE_PROJECT_FAILURE = "MOVE_PROJECT_FAILURE";

// Preferences
export const GET_PREFERENCES = "GET_PREFERENCES";
export const GET_PREFERENCES_LOADING = "GET_PREFERENCES_LOADING";
export const GET_PREFERENCES_SUCCESS = "GET_PREFERENCES_SUCCESS";
export const GET_PREFERENCES_FAILURE = "GET_PREFERENCES_FAILURE";
export const UPDATE_PREFERENCES = "UPDATE_PREFERENCES";
export const UPDATE_PREFERENCES_LOADING = "UPDATE_PREFERENCES_LOADING";
export const UPDATE_PREFERENCES_FAILURE = "UPDATE_PREFERENCES_FAILURE";
export const UPDATE_PREFERENCES_SUCCESS = "UPDATE_PREFERENCES_SUCCESS";

// Theme
export const CHANGE_THEME = "CHANGE_THEME";

// Users
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_LOADING = "REGISTER_USER_LOADING";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_USER = "GET_USER";
export const GET_USER_LOADING = "GET_USER_LOADING";
export const GET_USER_FAILURE = "GET_USER_FAILURE";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";

// Authentication
export const LOG_IN = "LOG_IN";
export const LOG_IN_LOADING = "LOG_IN_LOADING";
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export const LOG_IN_FAILURE = "LOG_IN_FAILURE";
export const LOG_OUT = "LOG_OUT";

// Drawer
export const OPEN_DRAWER = "OPEN_DRAWER";
export const CLOSE_DRAWER = "CLOSE_DRAWER";
export const TOGGLE_DRAWER = "TOGGLE_DRAWER";

// Images
export const CREATE_IMAGE = "CREATE_IMAGE";
export const CREATE_IMAGE_LOADING = "CREATE_IMAGE_LOADING";
export const CREATE_IMAGE_SUCCESS = "CREATE_IMAGE_SUCCESS";
export const CREATE_IMAGE_FAILURE = "CREATE_IMAGE_FAILURE";
export const UPDATE_IMAGE = "UPDATE_IMAGE";
export const UPDATE_IMAGE_LOADING = "UPDATE_IMAGE_LOADING";
export const UPDATE_IMAGE_SUCCESS = "UPDATE_IMAGE_SUCCESS";
export const UPDATE_IMAGE_FAILURE = "UPDATE_IMAGE_FAILURE";
