// Projects
export const GET_PROJECTS = "GET_PROJECTS";
export const GET_PROJECTS_LOADING = "GET_PROJECTS_LOADING";
export const GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS";
export const GET_PROJECTS_FAILURE = "GET_PROJECTS_FAILURE";
export const SET_ACTIVE_PROJECT = "SET_ACTIVE_PROJECT";

// Preferences
export const GET_PREFERENCES = "GET_PREFERENCES";
export const GET_PREFERENCES_LOADING = "GET_PREFERENCES_LOADING";
export const GET_PREFERENCES_SUCCESS = "GET_PREFERENCES_SUCCESS";
export const GET_PREFERENCES_FAILURE = "GET_PREFERENCES_FAILURE";

// Drawer
export const TOGGLE_DRAWER = "TOGGLE_DRAWER";

// Image Dialog
export const OPEN_IMAGE_DIALOG = "OPEN_IMAGE_DIALOG";
export const CLOSE_IMAGE_DIALOG = "CLOSE_IMAGE_DIALOG";

// Nav
export const CHANGE_NAV_HEIGHT = "CHANGE_NAV_HEIGHT";

// Theme
export const CHANGE_THEME = "CHANGE_THEME";

// Admin
export const GO_TO_ADMIN_CLIENT = "GO_TO_ADMIN_CLIENT";

// Users
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_LOADING = "REGISTER_USER_LOADING";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";
export const OPEN_USER_LOGIN_DIALOG = "OPEN_USER_LOGIN_DIALOG";
export const CLOSE_USER_LOGIN_DIALOG = "CLOSE_USER_LOGIN_DIALOG";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_USER = "GET_USER";
export const GET_USER_LOADING = "GET_USER_LOADING";
export const GET_USER_FAILURE = "GET_USER_FAILURE";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";

// Authentication
export const LOG_IN = "LOG_IN";
export const LOG_IN_LOADING = "LOG_IN_LOADING";
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export const LOG_IN_FAILURE = "LOG_IN_FAILURE";
export const LOG_OUT = "LOG_OUT";

// Quote Dialog
export const OPEN_QUOTE_DIALOG = "OPEN_QUOTE_DIALOG";
export const CLOSE_QUOTE_DIALOG = "CLOSE_QUOTE_DIALOG";

// Messages
export const SEND_MESSAGE = "SEND_MESSAGE";
export const SEND_MESSAGE_LOADING = "SEND_MESSAGE_LOADING";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAILURE = "SEND_MESSAGE_FAILURE";
